insert
into `T_MAIL_SEND_MANAGED`(
    `DATA_COLLECTION_SEQ`
    , `DETECTION_DATETIME`
    , `LIMIT_SUB_NO`
    , `MAIL_SEND_SEQ`
    , `SEND_STATUS`
    , `CREATED_AT`
    , `UPDATED_AT`
    , `VERSION`
)
values  (
    4
    , '2021/08/05 11:59:00.000'
    , '1'
    , 72
    , '2'
    , CURRENT_TIMESTAMP
    , CURRENT_TIMESTAMP
    , 0
)
on duplicate key update
	DATA_COLLECTION_SEQ = values(DATA_COLLECTION_SEQ)
	, DETECTION_DATETIME = values(DETECTION_DATETIME)
	, LIMIT_SUB_NO = values(LIMIT_SUB_NO)
	, MAIL_SEND_SEQ = values(MAIL_SEND_SEQ)
	, SEND_STATUS = values(SEND_STATUS)
	, UPDATED_AT = CURRENT_TIMESTAMP
	, VERSION = VERSION +1
;
